import secrets

from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

# Characters excluded from generated confirmation codes because they're easy
# to mis-key or mis-read off a phone screen: 0/O, 1/I/l.
_CONFIRMATION_CODE_ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz'


def generate_application_token():
    """A random, unguessable token for the public apply-flow link
    (Candidate.application_token) - 64 hex characters (32 bytes of entropy),
    generated with `secrets` (not `random`) since it doubles as the only
    thing standing between the public and someone else's prescreen/scheduling
    page."""
    return secrets.token_hex(32)


def generate_confirmation_code():
    """A short, human-readable code for the public status-lookup page
    (Interview.confirmation_code) - 9 characters from an alphabet with
    visually-ambiguous characters removed, since candidates may read this off
    a screen or type it in by hand. Not unique by construction - callers must
    retry on a collision (astronomically rare at this length/alphabet, but
    the column is still declared unique to make it a hard guarantee, not a
    hopeful one)."""
    return ''.join(secrets.choice(_CONFIRMATION_CODE_ALPHABET) for _ in range(9))


def iso_utc(dt):
    """Serializes a naive UTC datetime (as produced by datetime.utcnow(), which
    is how every timestamp in this app is stored) with an explicit 'Z' suffix.
    Without it, JS's `new Date(iso)` treats an offset-less date-time string as
    *local* time rather than UTC, silently shifting it by the browser's
    timezone offset — same clock digits, wrong instant."""
    return dt.isoformat() + 'Z' if dt else None


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(120), nullable=False)
    last_name = db.Column(db.String(120), nullable=False)
    phone = db.Column(db.String(20))
    # This interviewer's own static video-meeting link (RingCentral, not a
    # per-interview link generated by the calendar provider) - see
    # routes/apply.py's submit_application, which reads this from the
    # assigned interviewer at booking time and stores it on the Interview
    # itself, so it's what actually goes out in the candidate's confirmation
    # email/status page.
    personal_meeting_link = db.Column(db.String(500))
    email = db.Column(db.String(120), nullable=False, unique=True)
    password_hash = db.Column(db.String(255), nullable=False)
    role = db.Column(db.String(50), default='recruiter')  # admin, recruiter, interviewer
    is_active = db.Column(db.Boolean, default=True, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    VALID_ROLES = ('admin', 'recruiter', 'interviewer')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @property
    def name(self):
        return f"{self.first_name} {self.last_name}".strip()

    def to_dict(self):
        return {
            "id": self.id,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "name": self.name,
            "phone": self.phone,
            "personal_meeting_link": self.personal_meeting_link,
            "email": self.email,
            "role": self.role,
            "is_active": self.is_active,
            "created_at": iso_utc(self.created_at)
        }


class CalendarConnection(db.Model):
    """A recruiter/interviewer's connected Microsoft/Outlook Calendar.
    Belongs to a User (not a Job or MeetingStageTemplate) — one connection
    is reusable across every stage that User is assigned to interview for,
    so it only needs to be connected once. unique=True on user_id means
    reconnecting overwrites the existing row (upsert) instead of creating a
    second connection."""
    __tablename__ = 'calendar_connections'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False, unique=True)
    account_email = db.Column(db.String(120), nullable=False)
    # Encrypted at rest with Fernet (see microsoft_calendar.encrypt_token) —
    # this is a long-lived credential (until revoked or rotated - Microsoft
    # sometimes issues a new one on refresh, see
    # microsoft_calendar.get_valid_access_token), unlike access_token below,
    # which is short-lived (~1 hour) and low-value if it ever leaked, so
    # it's kept in plaintext the same way a session token would be.
    encrypted_refresh_token = db.Column(db.Text, nullable=False)
    access_token = db.Column(db.Text, nullable=True)
    token_expiry = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # backref='calendar_connection' mirrors Job.candidates below
    # (backref='job') — the FK lives here, User just gets the reverse
    # accessor. uselist=False since it's one connection per user.
    user = db.relationship('User', backref=db.backref('calendar_connection', uselist=False))

    def to_dict(self):
        return {
            "id": self.id,
            "user_id": self.user_id,
            "account_email": self.account_email,
            "created_at": iso_utc(self.created_at),
        }


class Job(db.Model):
    __tablename__ = 'jobs'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    status = db.Column(db.String(50), default='Draft')  # Published, Draft, Closed
    job_type = db.Column(db.JSON, default=list)  # subset of VALID_JOB_TYPES
    city = db.Column(db.String(120))
    state = db.Column(db.String(60))
    postal_code = db.Column(db.String(20))
    country = db.Column(db.String(60), default='USA')
    min_salary = db.Column(db.Float)
    max_salary = db.Column(db.Float)
    salary_period = db.Column(db.String(20))  # Hourly, Salary
    highlights = db.Column(db.JSON, default=list)  # free-form tags, e.g. "401(k)"
    description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    VALID_STATUSES = ('Published', 'Draft', 'Closed')
    VALID_JOB_TYPES = ('Full-time', 'Part-time', 'Remote')
    VALID_SALARY_PERIODS = ('Hourly', 'Salary')

    candidates = db.relationship('Candidate', backref='job', lazy=True)
    meeting_stage_templates = db.relationship(
        'MeetingStageTemplate', backref='job', cascade='all, delete-orphan', lazy=True
    )

    @property
    def location(self):
        return ", ".join(filter(None, [self.city, self.state])) or None

    @property
    def screening_questions(self):
        """Every pre-screening question across all of this job's stages —
        questions live on a stage (see MeetingStageTemplate.screening_questions)
        but a candidate applying to the job answers all of them, regardless of
        which stage each one belongs to."""
        return [
            q
            for t in sorted(self.meeting_stage_templates, key=lambda t: (t.sort_order, t.id))
            for q in sorted(t.screening_questions, key=lambda q: (q.sort_order, q.id))
        ]

    @property
    def onboarding_items(self):
        """Every onboarding document item across all of this job's stages —
        same aggregation as screening_questions above, for the same reason: a
        candidate applying to the job is on the hook for all of them,
        regardless of which stage each one belongs to."""
        return [
            item
            for t in sorted(self.meeting_stage_templates, key=lambda t: (t.sort_order, t.id))
            for item in sorted(t.onboarding_items, key=lambda i: (i.sort_order, i.id))
        ]

    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "status": self.status,
            "job_type": self.job_type or [],
            "city": self.city,
            "state": self.state,
            "postal_code": self.postal_code,
            "country": self.country,
            "location": self.location,
            "min_salary": self.min_salary,
            "max_salary": self.max_salary,
            "salary_period": self.salary_period,
            "highlights": self.highlights or [],
            "description": self.description,
            "created_at": iso_utc(self.created_at),
            "candidate_count": len(self.candidates),
            "meeting_stages": [
                t.to_dict()
                for t in sorted(self.meeting_stage_templates, key=lambda t: (t.sort_order, t.id))
            ]
        }


class MeetingStageTemplate(db.Model):
    __tablename__ = 'meeting_stage_templates'

    id = db.Column(db.Integer, primary_key=True)
    job_id = db.Column(db.Integer, db.ForeignKey('jobs.id'), nullable=False)
    meeting_type = db.Column(db.String(50), nullable=False)
    stage_name = db.Column(db.String(100), nullable=False)  # e.g. CHHA, Orientation
    duration_minutes = db.Column(db.Integer)  # only meaningful for interview-type stages
    # Only meaningful for 'In-person orientation' - how many candidates a
    # single session of this stage is meant to hold. This is a *default* the
    # frontend pre-fills the capacity field with when adding a session for
    # this stage - each session still stores its own Interview.capacity and
    # can be set differently after the fact; nothing here enforces a cap.
    default_capacity = db.Column(db.Integer)
    # Only meaningful for the two in-person types. Same "default, not
    # enforced" relationship to Interview.location as default_capacity has to
    # Interview.capacity above.
    location = db.Column(db.String(255))
    instructions = db.Column(db.Text)  # optional - directions, suite number, etc.
    # How far in advance a candidate can book a session for this stage.
    scheduling_window_days = db.Column(db.Integer, default=7, nullable=False)
    sort_order = db.Column(db.Integer, default=0, nullable=False)
    # Which recruiter/interviewer's connected Microsoft/Outlook Calendar the
    # public apply flow checks for availability and books onto (see
    # microsoft_calendar.py / CalendarConnection - one connection per User,
    # reused across every stage they're assigned to). Nullable: a stage with
    # no interviewer assigned (or whose assigned User hasn't connected a
    # calendar) simply has no bookable slots via the public flow -
    # routes/apply.py fails safe on that rather than falling back to some
    # other calendar.
    interviewer_user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    VALID_MEETING_TYPES = (
        'Virtual interview',
        'In-person interview',
        'In-person orientation',
        'Instant meeting link',
    )

    screening_questions = db.relationship(
        'ScreeningQuestion', backref='meeting_stage_template', cascade='all, delete-orphan', lazy=True
    )
    onboarding_items = db.relationship(
        'OnboardingDocumentItem', backref='meeting_stage_template', cascade='all, delete-orphan', lazy=True
    )
    interviewer = db.relationship('User')

    def to_dict(self):
        return {
            "id": self.id,
            "job_id": self.job_id,
            "meeting_type": self.meeting_type,
            "stage_name": self.stage_name,
            "duration_minutes": self.duration_minutes,
            "default_capacity": self.default_capacity,
            "location": self.location,
            "instructions": self.instructions,
            "scheduling_window_days": self.scheduling_window_days,
            "sort_order": self.sort_order,
            "interviewer_user_id": self.interviewer_user_id,
            "interviewer_name": self.interviewer.name if self.interviewer else None,
        }


class ScreeningQuestion(db.Model):
    """A pre-screening question defined on a meeting stage (the Stage editor's
    "Pre-screen" tab). Candidates progressing through the job get one
    CandidateScreeningAnswer per question, across all of the job's stages —
    see Job.screening_questions."""
    __tablename__ = 'screening_questions'

    id = db.Column(db.Integer, primary_key=True)
    meeting_stage_template_id = db.Column(
        db.Integer, db.ForeignKey('meeting_stage_templates.id'), nullable=False
    )
    question_text = db.Column(db.String(500), nullable=False)
    question_label = db.Column(db.String(200))  # short internal name, e.g. "Car insurance"
    # A multiple-choice question candidates pick one option from. Both empty
    # (list, not None) means a free-text question with no fixed options.
    answer_options = db.Column(db.JSON, default=list, nullable=False)
    # Subset of answer_options that qualifies a candidate to proceed — anything
    # picked that isn't in here is a disqualifying answer.
    qualified_answers = db.Column(db.JSON, default=list, nullable=False)
    sort_order = db.Column(db.Integer, default=0, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "meeting_stage_template_id": self.meeting_stage_template_id,
            "question_text": self.question_text,
            "question_label": self.question_label,
            "answer_options": self.answer_options or [],
            "qualified_answers": self.qualified_answers or [],
            "sort_order": self.sort_order,
        }


class OnboardingDocumentItem(db.Model):
    """A required (or optional) onboarding document defined on a meeting stage
    (the Stage editor's "Onboarding" tab). Candidates progressing through the
    job submit one CandidateDocument per item, across all of the job's stages
    — see Job.onboarding_items. Mirrors ScreeningQuestion's shape/scoping."""
    __tablename__ = 'onboarding_document_items'

    id = db.Column(db.Integer, primary_key=True)
    meeting_stage_template_id = db.Column(
        db.Integer, db.ForeignKey('meeting_stage_templates.id'), nullable=False
    )
    description = db.Column(db.String(500), nullable=False)
    # Named item_type, not type, to avoid shadowing the builtin - same reason
    # Interview.meeting_type isn't just called type. Only 'file_upload' exists
    # today; kept as a field for other item types later (e.g. an e-sign doc).
    item_type = db.Column(db.String(30), default='file_upload', nullable=False)
    required = db.Column(db.Boolean, default=True, nullable=False)
    sort_order = db.Column(db.Integer, default=0, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    VALID_TYPES = ('file_upload',)

    def to_dict(self):
        return {
            "id": self.id,
            "meeting_stage_template_id": self.meeting_stage_template_id,
            "description": self.description,
            "type": self.item_type,
            "required": self.required,
            "sort_order": self.sort_order,
        }


interview_candidates = db.Table(
    'interview_candidates',
    db.Column('interview_id', db.Integer, db.ForeignKey('interviews.id'), primary_key=True),
    db.Column('candidate_id', db.Integer, db.ForeignKey('candidates.id'), primary_key=True),
)


class Interview(db.Model):
    __tablename__ = 'interviews'

    id = db.Column(db.Integer, primary_key=True)
    job_id = db.Column(db.Integer, db.ForeignKey('jobs.id'), nullable=True)
    # Nullable: an interview not tied to a job (job_id is None) can't be tied to
    # one of that job's stages either. stage_name stays the source of truth for
    # display and for ad-hoc interviews with no template; this FK is the real
    # link back to the template when there is one, instead of matching by name.
    meeting_stage_template_id = db.Column(
        db.Integer, db.ForeignKey('meeting_stage_templates.id'), nullable=True
    )
    stage_name = db.Column(db.String(100), nullable=False)  # e.g. Orientation, Technical Interview, Onsite
    meeting_type = db.Column(db.String(50), nullable=False)  # Interview, Orientation, or Other
    location = db.Column(db.String(255))  # room, address, or meeting link
    scheduled_start = db.Column(db.DateTime, nullable=False)
    scheduled_end = db.Column(db.DateTime, nullable=False)
    capacity = db.Column(db.Integer, default=1, nullable=False)
    # The three columns below are only populated for an interview booked
    # through the public apply flow (routes/apply.py) - null for anything a
    # recruiter creates directly (manual sessions, ad-hoc interviews).
    # 9-char human-typeable code a candidate uses on the public status-lookup
    # page (see models.generate_confirmation_code) instead of needing an
    # account/login.
    confirmation_code = db.Column(db.String(9), unique=True, index=True, nullable=True)
    # The Microsoft Teams meeting link from the created calendar event's
    # onlineMeeting.joinUrl - duplicated here (rather than only ever
    # re-fetched from Microsoft) so the status page and confirmation email
    # can display it without another API call.
    meeting_link = db.Column(db.String(500), nullable=True)
    # Calendar event id backing this interview, so it can later be
    # updated/cancelled on the calendar provider's side (e.g. if a recruiter
    # cancels the interview in-app) - not exposed via to_dict, internal
    # bookkeeping only.
    calendar_event_id = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    VALID_MEETING_TYPES = ('Interview', 'Orientation', 'Other')

    job = db.relationship('Job', backref='interviews')
    meeting_stage_template = db.relationship('MeetingStageTemplate')
    candidates = db.relationship('Candidate', secondary=interview_candidates, backref='interviews')

    def to_dict(self):
        return {
            "id": self.id,
            "job_id": self.job_id,
            "job_title": self.job.title if self.job else None,
            "meeting_stage_template_id": self.meeting_stage_template_id,
            "stage_name": self.stage_name,
            "meeting_type": self.meeting_type,
            "location": self.location,
            "scheduled_start": iso_utc(self.scheduled_start),
            "scheduled_end": iso_utc(self.scheduled_end),
            "capacity": self.capacity,
            "scheduled_count": len(self.candidates),
            "candidates": [{"id": c.id, "name": c.display_name} for c in self.candidates],
            "confirmation_code": self.confirmation_code,
            "meeting_link": self.meeting_link,
            "created_at": iso_utc(self.created_at)
        }


class Candidate(db.Model):
    __tablename__ = 'candidates'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(120), nullable=False)
    phone = db.Column(db.String(20))
    job_id = db.Column(db.Integer, db.ForeignKey('jobs.id'), nullable=True)
    stage = db.Column(db.String(50), default='Applied')  # e.g. Applied, Interview, Offer, Hired, Rejected
    status = db.Column(db.String(50), default='Active')
    interviewer = db.Column(db.String(120))
    scheduled = db.Column(db.Boolean, default=False)
    city = db.Column(db.String(120))
    state = db.Column(db.String(60))
    # Street address - only collected via the public apply flow today
    # (routes/apply.py); candidates added by hand have this null, same as
    # resume below.
    address_line1 = db.Column(db.String(255))
    postal_code = db.Column(db.String(20))
    source = db.Column(db.String(120))  # e.g. Indeed, Referral
    resume_original_filename = db.Column(db.String(255))
    resume_stored_filename = db.Column(db.String(255))
    # Answers to the public apply flow's two fixed work-eligibility
    # questions (routes/apply.py) - null for candidates who didn't come
    # through that flow. Deliberately informational only: neither one blocks
    # submission or auto-disqualifies a candidate; a recruiter reviews them
    # like anything else on the candidate's profile.
    work_authorized = db.Column(db.Boolean, nullable=True)
    requires_visa_sponsorship = db.Column(db.Boolean, nullable=True)
    # The public apply flow's link back to this candidate's prescreen +
    # scheduling page (routes/apply.py) - null for candidates added by hand
    # instead. 64 hex chars from
    # models.generate_application_token; expires_at bounds how long that link
    # stays live, both to fail closed on a stale email and so dedupe (same
    # email+job re-applying) knows whether the existing row is still "live".
    application_token = db.Column(db.String(64), unique=True, index=True, nullable=True)
    application_token_expires_at = db.Column(db.DateTime, nullable=True)
    # Set the moment this candidate becomes disqualified - either
    # automatically, by the public apply flow evaluating their screening
    # answers (routes/apply.py's apply()), or manually, by a recruiter
    # setting a stage's status to 'Rejected' after an interview (routes/
    # candidates.py's update_stage_progress). Null for everyone else
    # (qualified, still-pending, or not through either path at all). Paired
    # with rejection_email_sent_at (also null until sent) so
    # scheduled_jobs.send_due_rejection_emails can find "disqualified more
    # than REJECTION_EMAIL_DELAY_MINUTES ago, not yet notified" without a
    # separate status enum. stage is set to 'Rejected' immediately (visible
    # to recruiters right away) independent of when the email actually goes
    # out.
    disqualified_at = db.Column(db.DateTime, nullable=True)
    rejection_email_sent_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    VALID_STAGES = ('Applied', 'Interview', 'Offer', 'Hired', 'Rejected')

    screening_answers = db.relationship(
        'CandidateScreeningAnswer', backref='candidate', cascade='all, delete-orphan', lazy=True
    )
    stage_progress = db.relationship(
        'CandidateStageProgress', backref='candidate', cascade='all, delete-orphan', lazy=True
    )
    documents = db.relationship(
        'CandidateDocument', backref='candidate', cascade='all, delete-orphan', lazy=True
    )

    @property
    def location(self):
        return ", ".join(filter(None, [self.city, self.state])) or None

    # Kept as properties (not just reading .name/.email/.phone directly)
    # since to_dict/to_detail_dict/Interview.to_dict's enrolled-candidate
    # list all go through these rather than the raw columns - a holdover
    # from when a candidate could be linked to their own self-registered
    # account (CandidateAccount) and these read live from there instead.
    # That concept was removed - candidates never get their own login; see
    # ApplicationStatusPage/routes/status.py for the phone/code-based
    # alternative - so these are direct passthroughs now, but keeping the
    # properties means nothing that already calls display_name/etc. needed
    # to change.
    @property
    def display_name(self):
        return self.name

    @property
    def display_email(self):
        return self.email

    @property
    def display_phone(self):
        return self.phone

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.display_name,
            "email": self.display_email,
            "phone": self.display_phone,
            "job_id": self.job_id,
            "job_title": self.job.title if self.job else None,
            "stage": self.stage,
            "status": self.status,
            "interviewer": self.interviewer,
            "scheduled": self.scheduled,
            "city": self.city,
            "state": self.state,
            "address_line1": self.address_line1,
            "postal_code": self.postal_code,
            "location": self.location,
            "source": self.source,
            "has_resume": self.resume_stored_filename is not None,
            "resume_filename": self.resume_original_filename,
            "work_authorized": self.work_authorized,
            "requires_visa_sponsorship": self.requires_visa_sponsorship,
            "created_at": iso_utc(self.created_at),
            "updated_at": iso_utc(self.updated_at or self.created_at),
            "current_stage": self._current_stage_summary(),
        }

    def _current_stage_summary(self):
        """The stage progress row to surface on the candidates list: the
        soonest upcoming one, else the most recently touched one."""
        if not self.stage_progress:
            return None
        upcoming = [p for p in self.stage_progress if p.status == 'Upcoming' and p.scheduled_at]
        if upcoming:
            progress = min(upcoming, key=lambda p: p.scheduled_at)
        else:
            progress = max(self.stage_progress, key=lambda p: p.updated_at or p.id)
        return {
            "meeting_stage_template_id": progress.meeting_stage_template_id,
            "stage_name": progress.meeting_stage_template.stage_name
            if progress.meeting_stage_template
            else None,
            "status": progress.status,
            "scheduled_at": iso_utc(progress.scheduled_at),
        }

    def to_detail_dict(self):
        data = self.to_dict()
        # Job.screening_questions is already ordered (by stage, then question
        # sort_order) — re-sorting by question sort_order alone would scramble
        # that, since sort_order only orders questions within their own stage.
        questions = self.job.screening_questions if self.job else []
        answers_by_question = {a.question_id: a.answer_text for a in self.screening_answers}
        progress_by_template = {p.meeting_stage_template_id: p for p in self.stage_progress}
        templates = (
            sorted(self.job.meeting_stage_templates, key=lambda t: (t.sort_order, t.id))
            if self.job
            else []
        )

        data.update(
            {
                "screening_answers": [
                    {
                        "question_id": q.id,
                        "question_text": q.question_text,
                        "answer_options": q.answer_options or [],
                        # Lets the recruiter UI show whether the given answer
                        # actually qualifies the candidate (see
                        # routes/apply.py's _is_qualifying_answer, which
                        # applies this same rule automatically for the
                        # public apply flow) rather than just whether it was
                        # answered at all.
                        "qualified_answers": q.qualified_answers or [],
                        "answer_text": answers_by_question.get(q.id),
                    }
                    for q in questions
                ],
                "stages": [
                    {
                        "meeting_stage_template_id": t.id,
                        "stage_name": t.stage_name,
                        "meeting_type": t.meeting_type,
                        # Whether this stage can be booked via a real calendar
                        # (routes/candidates.py's get_available_slots/
                        # book_stage_slot) - lets the frontend show the live
                        # availability picker instead of a plain date/time
                        # field for a stage set up that way (interview stages
                        # always have been; orientation optionally can be too).
                        "interviewer_user_id": t.interviewer_user_id,
                        "duration_minutes": t.duration_minutes,
                        **(
                            progress_by_template[t.id].to_dict()
                            if t.id in progress_by_template
                            else {
                                "id": None,
                                "status": 'Upcoming',
                                "scheduled_at": None,
                                "location": None,
                                "notes": None,
                                "score_communication": None,
                                "score_energy": None,
                                "score_relevant_experience": None,
                                "cancellation_reason": None,
                                "prompt_reschedule": None,
                                "has_recording": False,
                                "recording_filename": None,
                            }
                        ),
                    }
                    for t in templates
                ],
                "documents": {d.onboarding_item_id: d.to_dict() for d in self.documents},
            }
        )
        return data


class CandidateScreeningAnswer(db.Model):
    __tablename__ = 'candidate_screening_answers'

    id = db.Column(db.Integer, primary_key=True)
    candidate_id = db.Column(db.Integer, db.ForeignKey('candidates.id'), nullable=False)
    question_id = db.Column(db.Integer, db.ForeignKey('screening_questions.id'), nullable=False)
    answer_text = db.Column(db.Text)

    __table_args__ = (db.UniqueConstraint('candidate_id', 'question_id', name='uq_candidate_question'),)

    def to_dict(self):
        return {
            "id": self.id,
            "candidate_id": self.candidate_id,
            "question_id": self.question_id,
            "answer_text": self.answer_text,
        }


class CandidateStageProgress(db.Model):
    """A candidate's progress through one of their job's meeting stages:
    scheduling, status, interviewer notes, and scorecard ratings."""
    __tablename__ = 'candidate_stage_progress'

    id = db.Column(db.Integer, primary_key=True)
    candidate_id = db.Column(db.Integer, db.ForeignKey('candidates.id'), nullable=False)
    meeting_stage_template_id = db.Column(
        db.Integer, db.ForeignKey('meeting_stage_templates.id'), nullable=False
    )
    status = db.Column(db.String(30), default='Upcoming', nullable=False)
    scheduled_at = db.Column(db.DateTime)
    location = db.Column(db.String(255))
    notes = db.Column(db.Text)
    score_communication = db.Column(db.Integer)
    score_energy = db.Column(db.Integer)
    score_relevant_experience = db.Column(db.Integer)
    # Set together when a recruiter cancels via the "Cancel interview" modal.
    # Neither triggers any actual notification today - there's no email/SMS
    # infrastructure in this app yet, and no candidate-facing reschedule flow
    # for prompt_reschedule to hand off to - they're just recorded so the
    # recruiter's stated intent isn't lost.
    cancellation_reason = db.Column(db.Text)
    prompt_reschedule = db.Column(db.Boolean)
    # The uploaded recording of this stage's interview (see
    # routes/candidates.py's upload_recording/download_recording) - stored
    # the same way as Candidate.resume_stored_filename (file_storage.py, on
    # disk under UPLOAD_FOLDER, UUID-prefixed). One per (candidate, stage),
    # same as the rest of this row - a candidate with two virtual-interview
    # stages gets two independent recordings.
    recording_original_filename = db.Column(db.String(255))
    recording_stored_filename = db.Column(db.String(255))
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # 'Upcoming' is set automatically by scheduling/rescheduling (routes/
    # candidates.py's book_stage_slot, routes/interviews.py's
    # enroll_candidate) - everything else here is a post-interview outcome a
    # recruiter sets by hand (or, for the two 'Yes' sub-states, the app
    # advances automatically - see routes/status.py's
    # _maybe_advance_to_information_received).
    #
    # The three 'Yes...' values are what gates the onboarding checklist on
    # the candidate's own status page (see routes/status.py's
    # _onboarding_checklist) - starts at 'Yes - Awaiting information' once a
    # recruiter records a positive outcome, then the app itself flips it to
    # 'Yes - Information received' once every required item for this stage
    # has a submission. Plain 'Yes' (no sub-state) also gates it, for a
    # stage that doesn't collect onboarding documents.
    #
    # 'No' mirrors the auto-disqualification path (screening answers) for a
    # candidate who doesn't work out at this stage, same as the "Cancel
    # interview" action - see routes/candidates.py's update_stage_progress,
    # which cascades it to Candidate.stage/disqualified_at too, not just
    # this row.
    VALID_STATUSES = (
        'Upcoming', 'Yes', 'Yes - Awaiting information', 'Yes - Information received',
        'No', 'Maybe', 'Hired', 'No show', 'No response', 'Needs review',
    )

    __table_args__ = (
        db.UniqueConstraint('candidate_id', 'meeting_stage_template_id', name='uq_candidate_stage'),
    )

    meeting_stage_template = db.relationship('MeetingStageTemplate')

    def to_dict(self):
        return {
            "id": self.id,
            "candidate_id": self.candidate_id,
            "meeting_stage_template_id": self.meeting_stage_template_id,
            "status": self.status,
            "scheduled_at": iso_utc(self.scheduled_at),
            "location": self.location,
            "notes": self.notes,
            "score_communication": self.score_communication,
            "score_energy": self.score_energy,
            "score_relevant_experience": self.score_relevant_experience,
            "cancellation_reason": self.cancellation_reason,
            "prompt_reschedule": self.prompt_reschedule,
            "has_recording": self.recording_stored_filename is not None,
            "recording_filename": self.recording_original_filename,
        }


class CandidateDocument(db.Model):
    __tablename__ = 'candidate_documents'

    id = db.Column(db.Integer, primary_key=True)
    candidate_id = db.Column(db.Integer, db.ForeignKey('candidates.id'), nullable=False)
    onboarding_item_id = db.Column(
        db.Integer, db.ForeignKey('onboarding_document_items.id'), nullable=False
    )
    original_filename = db.Column(db.String(255), nullable=False)
    stored_filename = db.Column(db.String(255), nullable=False)
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.UniqueConstraint('candidate_id', 'onboarding_item_id', name='uq_candidate_onboarding_item'),
    )

    onboarding_item = db.relationship('OnboardingDocumentItem')

    def to_dict(self):
        return {
            "id": self.id,
            "onboarding_item_id": self.onboarding_item_id,
            "original_filename": self.original_filename,
            "uploaded_at": iso_utc(self.uploaded_at),
        }


class Organization(db.Model):
    """This deployment's single organization record (single-tenant app - one
    row, always id=1). Replaces the name that used to be hardcoded in the
    frontend (register pages' SMS-consent copy, the header's account
    dropdown). Logo/banner are stored the same way CandidateDocument stores
    uploads (file_storage.py's organization_file_path family) - the columns
    here just hold which stored filename to serve, not raw bytes."""
    __tablename__ = 'organizations'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    logo_original_filename = db.Column(db.String(255))
    logo_stored_filename = db.Column(db.String(255))
    banner_original_filename = db.Column(db.String(255))
    banner_stored_filename = db.Column(db.String(255))
    # Bounds the public apply flow's candidate-visible availability
    # (microsoft_calendar.get_free_slots) on top of whatever getSchedule
    # reports - the calendar API only knows busy/free, not "reasonable hours
    # (or days) to schedule a candidate". Editable from the Organization Settings
    # page (routes/organization.py) - these used to be env-var-only
    # (config.py's SCHEDULING_* values), moved here so a recruiter can change
    # them without a deploy. scheduling_days is a list of Python
    # date.weekday() ints (Monday=0 .. Sunday=6); default is Mon-Fri.
    scheduling_timezone = db.Column(db.String(64), default='UTC', nullable=False)
    scheduling_working_hours_start = db.Column(db.Integer, default=9, nullable=False)  # 24h, local to scheduling_timezone
    scheduling_working_hours_end = db.Column(db.Integer, default=17, nullable=False)
    scheduling_days = db.Column(db.JSON, default=lambda: [0, 1, 2, 3, 4], nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "has_logo": self.logo_stored_filename is not None,
            "has_banner": self.banner_stored_filename is not None,
            "scheduling_timezone": self.scheduling_timezone,
            "scheduling_working_hours_start": self.scheduling_working_hours_start,
            "scheduling_working_hours_end": self.scheduling_working_hours_end,
            "scheduling_days": self.scheduling_days or [],
        }


class BlocklistEntry(db.Model):
    """An email address or email domain barred from becoming a candidate -
    checked on the public apply flow (routes/apply.py) and when a recruiter
    adds a candidate by hand (routes/candidates.py)."""
    __tablename__ = 'blocklist_entries'

    id = db.Column(db.Integer, primary_key=True)
    entry_type = db.Column(db.String(10), nullable=False)  # 'email' or 'domain'
    value = db.Column(db.String(255), nullable=False)  # lowercased; a bare domain for 'domain' entries
    reason = db.Column(db.String(255))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    VALID_TYPES = ('email', 'domain')

    __table_args__ = (db.UniqueConstraint('entry_type', 'value', name='uq_blocklist_type_value'),)

    def to_dict(self):
        return {
            "id": self.id,
            "type": self.entry_type,
            "value": self.value,
            "reason": self.reason,
            "created_at": iso_utc(self.created_at),
        }


def is_email_blocked(email):
    """True if `email` (or its domain) has a matching BlocklistEntry. Shared
    by candidate self-registration and the recruiter's "add candidate" form
    so both enforce the same list the same way."""
    email = (email or '').strip().lower()
    if not email:
        return False
    domain = email.split('@')[-1] if '@' in email else None
    query = BlocklistEntry.query.filter(
        db.or_(
            db.and_(BlocklistEntry.entry_type == 'email', BlocklistEntry.value == email),
            db.and_(BlocklistEntry.entry_type == 'domain', BlocklistEntry.value == domain),
        )
    )
    return query.first() is not None
