"""scope screening questions to meeting stage

Revision ID: 213d189a3b5f
Revises: 8f8d57bef010
Create Date: 2026-08-18 11:42:02.837908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d189a3b5f'
down_revision = '8f8d57bef010'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff: this migration is scoped to the
# screening-questions restructuring only. Autogenerate also picked up several
# pre-existing, unrelated drifts between the dev DB and models.py (VARCHAR
# length/JSON-vs-TEXT differences from before this project used Alembic, two
# stray `jobs.department`/`jobs.location` columns nothing reads anymore, and
# a couple of NOT NULL constraints never enforced at the DB level) — left
# alone here so this migration doesn't silently touch unrelated columns;
# worth its own follow-up migration if/when someone wants to clean that up.
#
# candidate_screening_answers gets dropped and recreated rather than having
# its FK altered in place: its original FK was created unnamed, which SQLite's
# batch-alter mode can't reliably target by name to drop. Safe here because
# nothing has ever written a row to this table yet (pre-screen answers are a
# newer feature) — if that's no longer true when this runs, back up first.


def upgrade():
    op.create_table(
        'screening_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_stage_template_id', sa.Integer(), nullable=False),
        sa.Column('question_text', sa.String(length=500), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['meeting_stage_template_id'], ['meeting_stage_templates.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('candidate_screening_answers')
    op.drop_table('job_screening_questions')
    op.create_table(
        'candidate_screening_answers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('answer_text', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id']),
        sa.ForeignKeyConstraint(['question_id'], ['screening_questions.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('candidate_id', 'question_id', name='uq_candidate_question'),
    )


def downgrade():
    op.drop_table('candidate_screening_answers')
    op.create_table(
        'job_screening_questions',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('job_id', sa.INTEGER(), nullable=False),
        sa.Column('question_text', sa.VARCHAR(length=500), nullable=False),
        sa.Column('sort_order', sa.INTEGER(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'candidate_screening_answers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('answer_text', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id']),
        sa.ForeignKeyConstraint(['question_id'], ['job_screening_questions.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('candidate_id', 'question_id', name='uq_candidate_question'),
    )
    op.drop_table('screening_questions')
