"""add location instructions default capacity to meeting stage templates

Revision ID: 255ddfa8e439
Revises: 7015c570a199
Create Date: 2026-08-19 14:26:03.675543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255ddfa8e439'
down_revision = '7015c570a199'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as the migrations before it —
# the pre-existing unrelated drift is left alone; see 213d189a3b5f for the
# first occurrence of this note.


def upgrade():
    with op.batch_alter_table('meeting_stage_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))


def downgrade():
    with op.batch_alter_table('meeting_stage_templates', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('location')
        batch_op.drop_column('default_capacity')
