"""add organization and blocklist_entries

Revision ID: 3f8b6c2a9d17
Revises: 6e2d4a9b7c1f
Create Date: 2026-08-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8b6c2a9d17'
down_revision = '6e2d4a9b7c1f'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as the migrations before it —
# the pre-existing unrelated drift is left alone; see 213d189a3b5f for the
# first occurrence of this note.


def upgrade():
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('logo_original_filename', sa.String(length=255), nullable=True),
        sa.Column('logo_stored_filename', sa.String(length=255), nullable=True),
        sa.Column('banner_original_filename', sa.String(length=255), nullable=True),
        sa.Column('banner_stored_filename', sa.String(length=255), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'blocklist_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entry_type', sa.String(length=10), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entry_type', 'value', name='uq_blocklist_type_value'),
    )


def downgrade():
    op.drop_table('blocklist_entries')
    op.drop_table('organizations')
