"""add question label and answer options to screening questions

Revision ID: 4d7a3c52ce34
Revises: 213d189a3b5f
Create Date: 2026-08-18 11:59:26.140970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7a3c52ce34'
down_revision = '213d189a3b5f'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as 213d189a3b5f — the
# pre-existing unrelated drift (VARCHAR/JSON type differences, the stray
# jobs.department/jobs.location columns, unenforced NOT NULLs) is left alone.


def upgrade():
    with op.batch_alter_table('screening_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_label', sa.String(length=200), nullable=True))
        # server_default so this is safe even if the table already has rows —
        # SQLite requires a default for a NOT NULL column added to a non-empty
        # table. Dropped again after backfilling so it matches the model,
        # which sets the default in Python (`default=list`), not in the DB.
        batch_op.add_column(
            sa.Column('answer_options', sa.JSON(), nullable=False, server_default='[]')
        )
        batch_op.add_column(
            sa.Column('qualified_answers', sa.JSON(), nullable=False, server_default='[]')
        )

    with op.batch_alter_table('screening_questions', schema=None) as batch_op:
        batch_op.alter_column('answer_options', server_default=None)
        batch_op.alter_column('qualified_answers', server_default=None)


def downgrade():
    with op.batch_alter_table('screening_questions', schema=None) as batch_op:
        batch_op.drop_column('qualified_answers')
        batch_op.drop_column('answer_options')
        batch_op.drop_column('question_label')
