"""add ringcentral connections and interview meeting id

Revision ID: 5f8b8ca374e5
Revises: bdbb0d9df5a4
Create Date: 2026-09-16 11:47:44.162400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8b8ca374e5'
down_revision = 'bdbb0d9df5a4'
branch_labels = None
depends_on = None


# Trimmed by hand from the autogenerated version - same unrelated local-dev
# drift noise as the previous migration (jobs.department/location,
# job_type/highlights TEXT->JSON, meeting_type length, a few NOT NULL
# flips). Only the two changes below are part of this migration.
def upgrade():
    op.create_table(
        'ringcentral_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('account_email', sa.String(length=120), nullable=False),
        sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
        sa.Column('access_token', sa.Text(), nullable=True),
        sa.Column('token_expiry', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ringcentral_meeting_id', sa.String(length=255), nullable=True))


def downgrade():
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('ringcentral_meeting_id')
    op.drop_table('ringcentral_connections')
