"""add personal_meeting_link to users

Revision ID: 6ab7d9747c78
Revises: ee3857e1933b
Create Date: 2026-09-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab7d9747c78'
down_revision = 'ee3857e1933b'
branch_labels = None
depends_on = None

# An interviewer's own static video-meeting link (RingCentral) - replaces
# relying on a per-interview link generated by the calendar provider (see
# microsoft_calendar.create_event, which no longer requests one). Nullable:
# an interviewer who hasn't set one yet just books with no meeting link,
# same as before this field existed.


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_meeting_link', sa.String(length=500), nullable=True))


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('personal_meeting_link')
