"""add cancellation_reason and prompt_reschedule to candidate stage progress

Revision ID: 6e2d4a9b7c1f
Revises: 9a1c2f7e5b3d
Create Date: 2026-08-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2d4a9b7c1f'
down_revision = '9a1c2f7e5b3d'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as the migrations before it —
# the pre-existing unrelated drift is left alone; see 213d189a3b5f for the
# first occurrence of this note.


def upgrade():
    with op.batch_alter_table('candidate_stage_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prompt_reschedule', sa.Boolean(), nullable=True))


def downgrade():
    with op.batch_alter_table('candidate_stage_progress', schema=None) as batch_op:
        batch_op.drop_column('prompt_reschedule')
        batch_op.drop_column('cancellation_reason')
