"""add calendar connections

Revision ID: 7015c570a199
Revises: 886509c441e4
Create Date: 2026-08-19 13:37:21.285286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7015c570a199'
down_revision = '886509c441e4'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as the migrations before it —
# the pre-existing unrelated drift (interviews.meeting_type, jobs.job_type/
# highlights/location/department, the two unenforced NOT NULLs) is left
# alone; see 213d189a3b5f for the first occurrence of this note.


def upgrade():
    op.create_table(
        'calendar_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('google_email', sa.String(length=120), nullable=False),
        sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
        sa.Column('access_token', sa.Text(), nullable=True),
        sa.Column('token_expiry', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_calendar_connections_user_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )


def downgrade():
    op.drop_table('calendar_connections')
