"""link candidates to candidate accounts

Revision ID: 886509c441e4
Revises: 2a3b3e4fd385
Create Date: 2026-08-18 21:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886509c441e4'
down_revision = '2a3b3e4fd385'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as the migrations before it —
# the pre-existing unrelated drift is left alone (see 213d189a3b5f).


def upgrade():
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_candidates_candidate_account_id', 'candidate_accounts', ['candidate_account_id'], ['id'],
        )


def downgrade():
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_candidates_candidate_account_id', type_='foreignkey')
        batch_op.drop_column('candidate_account_id')
