"""add interview meeting stage template fk

Revision ID: 8f8d57bef010
Revises: c0a51148829e
Create Date: 2026-08-18 11:09:09.119341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8d57bef010'
down_revision = 'c0a51148829e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_stage_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_interviews_meeting_stage_template_id',
            'meeting_stage_templates', ['meeting_stage_template_id'], ['id'],
        )

    # ### end Alembic commands ###

    # Backfill: link every existing interview to its meeting stage template by
    # matching (job_id, stage_name) — the same pairing every write path in the
    # app has always used to derive stage_name in the first place. From here
    # on, renames cascade via this FK instead of by re-matching names.
    op.execute("""
        UPDATE interviews
        SET meeting_stage_template_id = (
            SELECT id FROM meeting_stage_templates
            WHERE meeting_stage_templates.job_id = interviews.job_id
              AND meeting_stage_templates.stage_name = interviews.stage_name
        )
        WHERE interviews.job_id IS NOT NULL
          AND EXISTS (
            SELECT 1 FROM meeting_stage_templates
            WHERE meeting_stage_templates.job_id = interviews.job_id
              AND meeting_stage_templates.stage_name = interviews.stage_name
          )
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interviews_meeting_stage_template_id', type_='foreignkey')
        batch_op.drop_column('meeting_stage_template_id')

    # ### end Alembic commands ###
