"""add onboarding document items, scope candidate documents to them

Revision ID: 9a1c2f7e5b3d
Revises: 255ddfa8e439
Create Date: 2026-08-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1c2f7e5b3d'
down_revision = '255ddfa8e439'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as the migrations before it —
# the pre-existing unrelated drift is left alone; see 213d189a3b5f for the
# first occurrence of this note.
#
# candidate_documents gets dropped and recreated (like candidate_screening_answers
# did in 213d189a3b5f, and for the same batch-alter/unnamed-FK reason) rather than
# having doc_type swapped for onboarding_item_id in place. Unlike that migration,
# this one is NOT a no-op on existing data: any CandidateDocument rows tied to the
# old fixed doc_type values (drivers_license/nursing_license/ssn_card/xray_ppd) are
# dropped here with no replacement, because there's no automatic mapping from those
# fixed strings to the new per-stage OnboardingDocumentItem rows — those don't exist
# until a recruiter creates matching items on a stage's "Onboarding" tab. The
# uploaded files themselves aren't touched (CandidateDocument.stored_filename isn't
# referenced anywhere else), so they become harmless orphans under
# uploads/candidates/<id>/ rather than being deleted. Confirmed acceptable for dev
# data; back up first if this ever runs against real submissions.


def upgrade():
    op.create_table(
        'onboarding_document_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_stage_template_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('item_type', sa.String(length=30), nullable=False),
        sa.Column('required', sa.Boolean(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['meeting_stage_template_id'], ['meeting_stage_templates.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    op.drop_table('candidate_documents')
    op.create_table(
        'candidate_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('onboarding_item_id', sa.Integer(), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('stored_filename', sa.String(length=255), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id']),
        sa.ForeignKeyConstraint(['onboarding_item_id'], ['onboarding_document_items.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('candidate_id', 'onboarding_item_id', name='uq_candidate_onboarding_item'),
    )


def downgrade():
    op.drop_table('candidate_documents')
    op.create_table(
        'candidate_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('doc_type', sa.String(length=30), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('stored_filename', sa.String(length=255), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('candidate_id', 'doc_type', name='uq_candidate_doctype'),
    )

    op.drop_table('onboarding_document_items')
