"""add reminder sent timestamps to candidate stage progress

Revision ID: bdbb0d9df5a4
Revises: 69453a9b28dd
Create Date: 2026-09-16 10:43:52.459934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbb0d9df5a4'
down_revision = '69453a9b28dd'
branch_labels = None
depends_on = None


# Trimmed by hand from the autogenerated version - the local dev SQLite file
# had unrelated pre-existing drift (jobs.department/location, job_type/
# highlights TEXT->JSON, meeting_type length, a few NOT NULL flips) that
# autogenerate picked up alongside the actual change here. None of that is
# part of this migration - only the three new columns below.
def upgrade():
    with op.batch_alter_table('candidate_stage_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_1day_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_4hr_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_1hr_sent_at', sa.DateTime(), nullable=True))


def downgrade():
    with op.batch_alter_table('candidate_stage_progress', schema=None) as batch_op:
        batch_op.drop_column('reminder_1hr_sent_at')
        batch_op.drop_column('reminder_4hr_sent_at')
        batch_op.drop_column('reminder_1day_sent_at')
