"""add scheduling window days to meeting stage templates

Revision ID: cf57f8e3d4ea
Revises: 4d7a3c52ce34
Create Date: 2026-08-18 12:38:03.756878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf57f8e3d4ea'
down_revision = '4d7a3c52ce34'
branch_labels = None
depends_on = None

# Hand-trimmed from the autogenerated diff, same as the two migrations before
# it — the pre-existing unrelated drift is left alone (see 213d189a3b5f).


def upgrade():
    with op.batch_alter_table('meeting_stage_templates', schema=None) as batch_op:
        # server_default so this is safe even though the table already has
        # rows — dropped again below since the model sets its default in
        # Python (`default=7`), not in the DB.
        batch_op.add_column(
            sa.Column('scheduling_window_days', sa.Integer(), nullable=False, server_default='7')
        )

    with op.batch_alter_table('meeting_stage_templates', schema=None) as batch_op:
        batch_op.alter_column('scheduling_window_days', server_default=None)


def downgrade():
    with op.batch_alter_table('meeting_stage_templates', schema=None) as batch_op:
        batch_op.drop_column('scheduling_window_days')
